Repository playframework/play-ws, pull requests merged in 2019-03, with the labels that each got.

#259 scala-java8-compat 0.9.0
  project/Dependencies.scala
Labels: status:backlog

#310 Update dependencies
  project/Dependencies.scala
Labels: status:needs-backport, type:updates

#313 Make it possible to enable/disable cookie store
  integration-tests/src/test/scala/play/api/libs/ws/ahc/AhcWSClientSpec.scala
  play-ahc-ws-standalone/src/main/resources/reference.conf
  play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
  play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java
  play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala
  project/Dependencies.scala
Labels: status:needs-backport
