Repository playframework/play-ws, pull requests merged in 2022-09, with the labels that each got.

#699 🔄 Synced file(s) with playframework/.github
  .mergify.yml
Labels: sync

#701 akka-stream 2.6.20 (was 2.6.19)
  project/Dependencies.scala
Labels: type:updates

#702 scala3-library 3.2.0 (was 3.1.3)
  .github/workflows/build-test.yml
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#700 logback-core 1.4.1 (was 1.2.11)
  project/Dependencies.scala
Labels: type:updates

#703 slf4j-api 2.0.1 (was 1.7.36)
  project/Dependencies.scala
Labels: type:updates
